## 该服务的端口信息
server:
  port: 9102

## 服务别名和nacos服务注册发现地址配置
spring:
  application:
    name: nacos-product
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        # 使用nginx
        server-addr: 188.131.134.70:80  ## 换成自己服务器的ip(由于nginx是监听的80端口后，请求负载均衡至3333、4444和5555)

## 监控相关
management.endpoints.web.exposure.include: '*'